project_id = "reservin"

[api]
enabled = true

[db]
port = 54322

[db.pooler]
enabled = false

[studio]
enabled = true
port = 54323

[auth]
enabled = true

[functions.create-reservation]
verify_jwt = false
